"""empty message

Revision ID: c115f41fe842
Revises: 9062e277100e
Create Date: 2020-04-23 08:21:38.257551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c115f41fe842'
down_revision = '9062e277100e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_unique_constraint('Comment', ['id'])

    with op.batch_alter_table('event_comments', schema=None) as batch_op:
        batch_op.create_unique_constraint('Event_Comment', ['id'])

    with op.batch_alter_table('event_posts', schema=None) as batch_op:
        batch_op.create_unique_constraint('Event_Post', ['id'])

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_unique_constraint('Post', ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=80), nullable=True))
        batch_op.create_unique_constraint('User', ['id'])
        batch_op.drop_column('friend_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('friend_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('title')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('event_posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('event_comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
