"""empty message

Revision ID: cab1d922e0f4
Revises: b47e5fba6bb2
Create Date: 2020-04-23 08:07:01.441915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cab1d922e0f4'
down_revision = 'b47e5fba6bb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('selected', sa.Integer(), nullable=True),
    sa.Column('default', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_title_association',
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('titles_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['titles_id'], ['titles.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], )
    )
    op.create_unique_constraint(None, 'comments', ['id'])
    op.create_unique_constraint(None, 'event_comments', ['id'])
    op.create_unique_constraint(None, 'event_posts', ['id'])
    op.create_unique_constraint(None, 'posts', ['id'])
    op.add_column('users', sa.Column('title', sa.String(length=80), nullable=True))
    op.create_unique_constraint(None, 'users', ['id'])
    op.drop_column('users', 'friend_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('friend_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'title')
    op.drop_constraint(None, 'posts', type_='unique')
    op.drop_constraint(None, 'event_posts', type_='unique')
    op.drop_constraint(None, 'event_comments', type_='unique')
    op.drop_constraint(None, 'comments', type_='unique')
    op.drop_table('user_title_association')
    op.drop_table('titles')
    # ### end Alembic commands ###
